### ISSUE TITLE
Minor issues and possible improvements

### ISSUE THREAD

**Issue by mgr0dzicki** [mimuw-jnp2-rust/project-matrix-busters#16]
Must:
- [x] Missing translation for "Matrix is invalid!\n". (#25)
- [X] Toasts saying text was copied into clipboard (otherwise it looks like nothing happening). (#26)
- [X] When operation results in error (for example tried to inverse non-square matrix) display a toast instead of putting the error message in the clipboard. (#26)
- [X] Document all features in README. (#27)

Should:
- [x] Digits in rendered objects are slightly misaligned.

Nice to:
- [ ] #33
- [x] #32
